import { useState, useEffect } from 'react';
import { Row, Col } from 'react-bootstrap';
import api from '../../api/axiosInstance';
import PageHeader from '../../components/shared/ui/PageHeader';
import DataTable from '../../components/shared/ui/DataTable';
import StatCard from '../../components/shared/ui/StatCard';
import StatusBadge from '../../components/shared/ui/StatusBadge';

export default function BillingPage() {
  const [records, setRecords] = useState([]); const [loading, setLoading] = useState(true);
  const [statusFilter, setStatusFilter] = useState('');

  useEffect(() => { api.get('/api/billing').then(r => setRecords(r.data || [])).catch(() => setRecords([])).finally(() => setLoading(false)); }, []);

  const filtered = statusFilter ? records.filter(r => r.status === statusFilter) : records;
  const count = s => records.filter(r => r.status === s).length;
  const columns = [
    { key:'id', label:'ID' }, { key:'issueId', label:'Issue ID' },
    { key:'chargeType', label:'Charge Type', render: v => <span className="status-badge primary">{v}</span> },
    { key:'amount', label:'Amount', render: v => v ? `₹${v}` : '—' },
    { key:'status', label:'Status', render: v => <StatusBadge status={v} /> },
    { key:'createdAt', label:'Created', render: v => v ? new Date(v).toLocaleString() : '—' },
  ];

  return (
    <div className="animate-fadein">
      <PageHeader title="Billing Records" subtitle="Auto-created when blood is issued" />
      <div className="alert-glass warning mb-4">Billing records are auto-generated by Kafka events. This is a read-only view.</div>
      <Row className="g-3 mb-4">
        <Col xs={6} md={3}><StatCard title="Total" value={records.length} color="primary" /></Col>
        <Col xs={6} md={3}><StatCard title="Pending" value={count('PENDING')} color="warning" /></Col>
        <Col xs={6} md={3}><StatCard title="Paid" value={count('PAID')} color="success" /></Col>
        <Col xs={6} md={3}><StatCard title="Waived" value={count('WAIVED')} color="primary" /></Col>
      </Row>
      <div className="filter-row mb-3">
        <select className="form-select" style={{ width:180 }} value={statusFilter} onChange={e => setStatusFilter(e.target.value)}>
          <option value="">All Statuses</option>
          {['PENDING','PAID','WAIVED','CANCELLED'].map(s => <option key={s}>{s}</option>)}
        </select>
      </div>
      <div className="table-wrapper"><DataTable columns={columns} data={filtered} loading={loading} /></div>
    </div>
  );
}
